name: Test

on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v1.0.2
        with:
          path: "."
          ext: ".yml"
  Test:
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: Output results
        run: |
          echo ${{ matrix.paths }}
  Release:
    if: github.ref_name == 'master'
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0
      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npx semantic-release
